version: "3.6"

services:
    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=thiago
            - RABBITMQ_DEFAULT_PASS=alura